name: Deploy on testapps.carmentis.io

on:
  push:
    branches: [master]

jobs:
  prepare:
    name: Prepare Hello World Application
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v4
      - name: Exporting Github environment variables into .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_APPLICATION_PORT: ${{ vars.APPLICATION_PORT }}
          file_name: .env
          fail_on_empty: false
          sort_keys: false
  deploy:
    name: Deploy Hello World Application
    runs-on: ubuntu-latest
    steps:
      - name: Copy Source to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ".,!node_modules"
          target: "/tmp/carmentis-app-hello-world"
      - name: Build and Run Hello World Application
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: "cd /tmp/carmentis-app-hello-world && ./build.sh"
