name: Deploy on testapps.carmentis.io

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy Hello World Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Creation of .env file
        run: touch .env
      - name: Exporting Github environment variables into .env file
        uses: krisalay/export-env@v1.0.0
        with:
          filename: .env
      - name: Copy Source to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ".,!node_modules"
          target: "/tmp/carmentis-app-hello-world"
      - name: Build and Run Hello World Application
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: "cd /tmp/carmentis-app-hello-world && ./build.sh"
